name: Go Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: write # For pushing changes
      issues: write # For commenting on issues
      pull-requests: write # For commenting on PRs
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Important for PR support

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt
        run: gofumpt -l -w .

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true' && github.event_name != 'pull_request'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Apply gofumpt formatting"
          git push

      - name: Push changes to PR
        if: steps.git-check.outputs.modified == 'true' && github.event_name == 'pull_request'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Apply gofumpt formatting"
          git push origin HEAD:${{ github.head_ref }}
